rule all:
  input:
    "AUS_emissions-year.png",
    "AUS_fires-year.png",
    "AUS_fires-emissions_scatter.png",
    "AUS_fires.png"

rule A:
  input:
    "Australia_fires.txt",
  output:
    "AUS_emissions-year.png"
  shell:
    "python " + "scatter.py --datafile Australia_fires.txt --x_col 0 --y_col 2 --x_label 'Year' --y_label 'Total Emissions' --title 'Australian Total Emissions by Year' --outfile 'AUS_emissions-year.png'"

rule B:
  input:
    "Australia_fires.txt",
  output:
    "AUS_fires-year.png"
  shell:
    "python " + "scatter.py --datafile Australia_fires.txt --x_col 0 --y_col 1 --x_label 'Year' --y_label 'Number of Forest Fires' --title 'Australian Forest Fires by Year' --outfile 'AUS_fires-year.png'"

rule C:
  input:
    "Australia_fires.txt",
  output:
    "AUS_fires-emissions_scatter.png"
  shell:
    "python " + "scatter.py --datafile Australia_fires.txt --x_col 2 --y_col 1 --x_label 'Total Emissions' --y_label 'Number Forest Fires' --title 'Australian Forest Fire Count vs Total Emissions' --outfile 'AUS_fires-emissions_scatter.png'"
    
rule D:
  input:
    "Australia_fires.txt",
  output:
    "AUS_fires.png"
  shell:
    "python " + "hist.py --datafile Australia_fires.txt --data_label 'Number of Forest Fires' --col_ndx 1 --title 'Australian Forest Fires' --outfile 'AUS_fires.png'"

rule E:
  output:
    "Australia_fires.txt"
  shell:
    "python " + "get_data.py --datafile ../../Agrofood_co2_emission.csv --outfile Australia_fires.txt --country Australia --x_datacol 'Forest fires' --y_datacol 'total_emission'"